"""
FedCloud JSON-to-Lean Translator

Converts structured JSON payloads from cloud telemetry sources into
typed Lean 4 definition files compatible with the FedCloud verification engine.

Supported input formats:
  - AWS Config resource inventory
  - Terraform plan JSON (tfplan.json)
  - Tyler Technologies application metadata schemas
  - Generic infrastructure state JSON

Output: A .lean file containing concrete type instantiations that can be
compiled alongside the invariant theorem library.
"""

import json
import sys
from pathlib import Path
from typing import Any


class LeanTranslator:
    """Translates JSON infrastructure state to Lean 4 definitions."""

    HEADER = """\
/-
  Auto-generated by FedCloud Translator
  Source: {source}

  DO NOT EDIT — this file is overwritten on each verification run.
  Modify the source JSON or the translator logic instead.
-/

import FedCloud.BaseModel
import FedCloud.Verify

open FedCloud

"""

    def __init__(self, source_label: str = "unknown"):
        self.source_label = source_label

    def translate_sessions(self, sessions: list[dict]) -> str:
        """Convert IAM/IdP session records to Lean Session list."""
        lines = []
        for s in sessions:
            user_id = s.get("user_id", s.get("userId", s.get("arn", "unknown")))
            is_priv = self._to_lean_bool(
                s.get("is_privileged", s.get("isAdmin", s.get("privileged", False)))
            )
            has_mfa = self._to_lean_bool(
                s.get("has_phishing_resistant_mfa", s.get("mfaType", "") in ("FIDO2", "WebAuthn", "phishing_resistant"))
            )
            # Parse token lifetime — accept minutes directly or seconds (convert)
            lifetime = s.get("token_lifetime_minutes", 0)
            if "token_lifetime_seconds" in s:
                lifetime = s["token_lifetime_seconds"] // 60

            lines.append(
                f'    {{ user_id := "{user_id}"\n'
                f'      is_privileged := {is_priv}\n'
                f'      has_phishing_resistant_mfa := {has_mfa}\n'
                f'      token_lifetime_minutes := {lifetime} }}'
            )
        return ",\n".join(lines)

    def translate_data_stores(self, stores: list[dict]) -> str:
        """Convert database/storage resource records to Lean DataStore list."""
        lines = []
        for d in stores:
            store_id = d.get("id", d.get("resourceId", d.get("arn", "unknown")))
            has_fed = self._to_lean_bool(
                d.get("contains_federal_data", d.get("classification", "") in ("federal", "cui", "pii"))
            )
            encrypted = self._to_lean_bool(
                d.get("is_encrypted_at_rest", d.get("encrypted", d.get("storageEncrypted", False)))
            )
            cipher = d.get(
                "cryptographic_module_standard",
                d.get("kmsKeySpec", d.get("cipher", "UNKNOWN"))
            )
            # Normalize known KMS key specs to FIPS standard names
            fips_map = {
                "SYMMETRIC_DEFAULT": "FIPS-140-3",
                "AES_256": "FIPS-140-3",
                "RSA_2048": "FIPS-140-3",
            }
            cipher = fips_map.get(cipher, cipher)

            lines.append(
                f'    {{ id := "{store_id}"\n'
                f'      contains_federal_data := {has_fed}\n'
                f'      is_encrypted_at_rest := {encrypted}\n'
                f'      cryptographic_module_standard := "{cipher}" }}'
            )
        return ",\n".join(lines)

    def translate_compute_resources(self, resources: list[dict]) -> str:
        """Convert EC2/EKS/Fargate records to Lean ComputeResource list."""
        lines = []
        for c in resources:
            res_id = c.get("id", c.get("resourceId", c.get("instanceId", "unknown")))
            signed = self._to_lean_bool(
                c.get("immutable_image_signature_valid", c.get("imageDigestVerified", False))
            )
            shell = self._to_lean_bool(
                c.get("allows_interactive_shell_access", c.get("sshEnabled", c.get("ssmEnabled", False)))
            )
            open_ingress = self._to_lean_bool(
                c.get("network_ingress_anywhere", c.get("openIngress", False))
            )

            lines.append(
                f'    {{ id := "{res_id}"\n'
                f'      immutable_image_signature_valid := {signed}\n'
                f'      allows_interactive_shell_access := {shell}\n'
                f'      network_ingress_anywhere := {open_ingress} }}'
            )
        return ",\n".join(lines)

    def translate_log_streams(self, streams: list[dict]) -> str:
        """Convert CloudTrail/CloudWatch log config to Lean LogStream list."""
        lines = []
        for l in streams:
            source_id = l.get("source_id", l.get("logGroupName", l.get("trailName", "unknown")))
            active = self._to_lean_bool(
                l.get("is_actively_streaming", l.get("isLogging", l.get("status", "") == "ACTIVE"))
            )
            tamper = self._to_lean_bool(
                l.get("destination_is_tamper_evident",
                      l.get("logFileValidationEnabled", l.get("objectLockEnabled", False)))
            )
            retention = l.get("retention_days", l.get("retentionInDays", 0))

            lines.append(
                f'    {{ source_id := "{source_id}"\n'
                f'      is_actively_streaming := {active}\n'
                f'      destination_is_tamper_evident := {tamper}\n'
                f'      retention_days := {retention} }}'
            )
        return ",\n".join(lines)

    def translate_full_state(self, data: dict) -> str:
        """Convert a complete infrastructure state JSON to a Lean definition file."""
        sessions = data.get("sessions", data.get("active_sessions", []))
        stores = data.get("databases", data.get("data_stores", data.get("deployed_stores", [])))
        compute = data.get("compute", data.get("nodes", data.get("instances", [])))
        logs = data.get("log_streams", data.get("logging", data.get("streams", [])))

        lean_code = self.HEADER.format(source=self.source_label)

        lean_code += "def currentState : FedCloud.Verify.SystemState :=\n"
        lean_code += "  { security_context :=\n"
        lean_code += "      { active_sessions :=\n"
        lean_code += "          [\n"
        lean_code += self.translate_sessions(sessions) + "\n"
        lean_code += "          ] }\n"
        lean_code += "    infrastructure :=\n"
        lean_code += "      { deployed_stores :=\n"
        lean_code += "          [\n"
        lean_code += self.translate_data_stores(stores) + "\n"
        lean_code += "          ] }\n"
        lean_code += "    topology :=\n"
        lean_code += "      { nodes :=\n"
        lean_code += "          [\n"
        lean_code += self.translate_compute_resources(compute) + "\n"
        lean_code += "          ] }\n"
        lean_code += "    logging :=\n"
        lean_code += "      { streams :=\n"
        lean_code += "          [\n"
        lean_code += self.translate_log_streams(logs) + "\n"
        lean_code += "          ] } }\n"

        return lean_code

    def translate_terraform_plan(self, tfplan: dict) -> dict:
        """
        Extract infrastructure state from a Terraform plan JSON.
        Normalizes tfplan.json resource changes into the generic state format.
        """
        state: dict[str, list] = {
            "sessions": [],
            "databases": [],
            "compute": [],
            "log_streams": [],
        }

        resources = tfplan.get("planned_values", {}).get("root_module", {}).get("resources", [])
        for r in resources:
            rtype = r.get("type", "")
            values = r.get("values", {})
            address = r.get("address", "unknown")

            if rtype in ("aws_db_instance", "aws_rds_cluster"):
                state["databases"].append({
                    "id": address,
                    "contains_federal_data": True,
                    "is_encrypted_at_rest": values.get("storage_encrypted", False),
                    "cryptographic_module_standard": "FIPS-140-3" if values.get("kms_key_id") else "NONE",
                })
            elif rtype in ("aws_s3_bucket", "aws_s3_bucket_server_side_encryption_configuration"):
                state["databases"].append({
                    "id": address,
                    "contains_federal_data": True,
                    "is_encrypted_at_rest": True if values.get("rule") else values.get("server_side_encryption_configuration") is not None,
                    "cryptographic_module_standard": "FIPS-140-3",
                })
            elif rtype in ("aws_instance", "aws_ecs_task_definition", "aws_eks_node_group"):
                state["compute"].append({
                    "id": address,
                    "immutable_image_signature_valid": bool(values.get("image_id") or values.get("container_definitions")),
                    "allows_interactive_shell_access": values.get("associate_public_ip_address", False),
                    "network_ingress_anywhere": False,
                })
            elif rtype == "aws_cloudwatch_log_group":
                state["log_streams"].append({
                    "source_id": address,
                    "is_actively_streaming": True,
                    "destination_is_tamper_evident": True,
                    "retention_days": values.get("retention_in_days", 0),
                })
            elif rtype == "aws_cloudtrail":
                state["log_streams"].append({
                    "source_id": address,
                    "is_actively_streaming": values.get("is_multi_region_trail", True),
                    "destination_is_tamper_evident": values.get("enable_log_file_validation", False),
                    "retention_days": 730,
                })

        return state

    @staticmethod
    def _to_lean_bool(value: Any) -> str:
        """Convert a Python value to a Lean Bool literal."""
        if isinstance(value, bool):
            return "true" if value else "false"
        if isinstance(value, str):
            return "true" if value.lower() in ("true", "yes", "1") else "false"
        return "true" if value else "false"


def translate_json_to_lean(json_path: str, output_path: str) -> None:
    """CLI entry point: translate a JSON state file to a Lean definition file."""
    with open(json_path, "r") as f:
        data = json.load(f)

    translator = LeanTranslator(source_label=json_path)

    # Auto-detect Terraform plan format
    if "planned_values" in data:
        data = translator.translate_terraform_plan(data)

    lean_code = translator.translate_full_state(data)

    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    with open(output, "w") as out:
        out.write(lean_code)

    print(f"Translated {json_path} -> {output_path}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python json_to_lean.py <input.json> <output.lean>")
        sys.exit(1)
    translate_json_to_lean(sys.argv[1], sys.argv[2])
